project:
  type: website

website:
  title: "PATH Malaria & NTDs Technical Docs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PATH-Global-Health/MNTD-tech-docs
      - icon: twitter
        href: https://twitter.com/PATHMalaria
  comments: 
    utterances:
      repo: PATH-Global-Health/MNTD-tech-docs
  google-analytics: "G-6DDVRC28MC"
      
format:
  html:
    theme: journal
    css: styles.scss

execute:
  freeze: auto
      
